#!/usr/bin/env bash

#
# add_centos_user_to_root_group
#
# Our main `whoami` user account needs to be able to do root-y stuff, like read
# and write directories that are owned by the `root` group; this script makes
# that possible
#

# Denote the start of adding the centos user to the root group
touch /etc/seashell/installs/add_centos_user_to_root_group.started

# Add the current user (centos) to the root group
sudo usermod -a -G root `whoami`
echo "Linux requires you log out and log back in, in order for the group changes to take effect for the `whoami` user"

# Denote the completion of adding the centos user to the root group
touch /etc/seashell/installs/add_centos_user_to_root_group.finished
