#!/usr/bin/env bash

#
# allow_opt_to_be_writable_by_root_group
#
# By default, the /opt folder in CentOS is not writable by anyone but the `root`
# user; we want to make it writable by anyone in the `root` group so that it can
# serve it's purpose of housing add-on application for non-`root` users
#

# Denote the start of allowing /opt to be writable by the root group
touch /etc/seashell/installs/allow_opt_to_be_writable_by_root_group.started

# Allow /opt to be writable by root
sudo chmod 0775 /opt

# Denote the completion of allowing /opt to be writable by the root group
touch /etc/seashell/installs/allow_opt_to_be_writable_by_root_group.finished
