#!/usr/bin/env bash

#
# baseline
#
# All systems we work with should have some sane basline packages and updates

# Denote the start of installing baseline
touch /etc/seashell/installs/baseline.started

# Update CentOS
sudo yum -y update

# Install the development tools bundle
sudo yum groupinstall -y 'development tools'

# Install Expect
sudo yum -y install expect

# Denote the completion of installing baseline
touch /etc/seashell/installs/baseline.finished
