#!/usr/bin/env bash

#
# disable_selinux
#
# SELinux is a nightmare, and Seashell always turns it off

cat << EOF | sudo tee /etc/sysconfig/selinux
SELINUX=disabled
SELINUXTYPE=targeted
EOF
echo "Linux requires you restart in order for SELinux to be disabled"
