#!/usr/bin/env bash

#
# disable_selinux
#
# SELinux is a nightmare, and Seashell always turns it off

# Denote the start of disabling SELinux
touch /etc/seashell/installs/disable_selinux.started

# Disable SELinux
cat << EOF | sudo tee /etc/sysconfig/selinux
SELINUX=disabled
SELINUXTYPE=targeted
EOF
echo "Linux requires you restart in order for SELinux to be disabled"

# Denote the completion of disabling SELinux
touch /etc/seashell/installs/disable_selinux.finished
