#!/usr/bin/env bash

#
# get_public_ec2_hostname
#
# This script prints out the AWS EC2 public hostname of this instance
# (This will only work on AWS EC2 instances)
#

curl http://169.254.169.254/latest/meta-data/public-hostname