#!/usr/bin/env bash

#
# install_airflow
#
# Install Airflow, with all Airflow packages

# Set up a virtualenv for Airflow
cd /opt/virtualenvs
virtualenv airflow

# Install libffi-dev
# (required for Airflow's crypto package)
sudo rpm -i http://195.220.108.108/linux/centos/7.3.1611/os/x86_64/Packages/libffi-devel-3.0.13-18.el7.x86_64.rpm
sudo yum -y install libffi-devel

# Make Airflow's home directory
mkdir /opt/airflow
echo export AIRFLOW_HOME=/opt/airflow >> /home/centos/.bash_profile
source /home/centos/.bash_profile

# Install Airflow, with all Airflow packages
cd /opt/airflow
/opt/virtualenvs/airflow/bin/pip install airflow[all]

# Initialize the Airflow database
/opt/virtualenvs/airflow/bin/airflow initdb

# Add Airflow's binary directory to the $PATH, so that Airflow can find the binaries it depends on, like gunicorn
echo PATH=\$PATH:/opt/virtualenvs/airflow/bin >> ~/.bash_profile
source /home/centos/.bash_profile

# Make a script that can start Airflow with all environmental variables
# (Perfect for use in non-interactive shells without Virtualenv's activate)
cat << EOF | sudo tee /opt/start_airflow
#!/usr/bin/env bash

VIRTUAL_ENV="/opt/virtualenvs/airflow" PATH="$VIRTUAL_ENV/bin:$PATH" AIRFLOW_HOME=/opt/airflow /opt/virtualenvs/airflow/bin/airflow webserver -p 8080

EOF
sudo chown centos:centos /opt/start_airflow
chmod +x /opt/start_airflow

# N.B., this is how you start the Airflow web server as a logged-in user
# /opt/virtualenvs/airflow/bin/airflow webserver -p 8080
