#!/usr/bin/env bash

#
# install_mysql_server
#
# This is intenended for localhost/development/Vagrant usage only; it is not hardened
# for production traffic
#

# Create a temporary directory at /tmp/install_mysql_client
mkdir /tmp/install_mysql_server
cd /tmp/install_mysql_server

# Download the MySQL server from Oracle
curl -L -O https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

# Install the MySQL 5.7 server
sudo rpm -ivh mysql57-community-release-el7-11.noarch.rpm
sudo yum -y install mysql-server

# Delete the temporary directory, since we're done with it
cd ~
rm -rf /tmp/install_mysql_server

# Start MySQL Server
sudo systemctl start mysqld

# Echo the status of MySQL Server to STDOUT, to prove it started
sudo systemctl status mysqld

# Save the random root password into the user's home directory
random_root_mysql_password=$(grep 'temporary.*root@localhost' /var/log/mysqld.log | tail -n 1 | sed 's/.*root@localhost: //')
cat << EOF | tee ~/mysql_root_password > /dev/null
$random_root_mysql_password
EOF

# Configure MySQL
expect -c "
set timeout 10
spawn mysql_secure_installation
expect \"Enter password for user root: \"
send \"$random_root_mysql_password\r\"
expect \"New password: \"
send \"$random_root_mysql_password\r\"
expect \"Change the password for root ? ((Press y|Y for Yes, any other key for No) : \"
send \"N\r\"
expect \"Remove anonymous users? (Press y|Y for Yes, any other key for No) : \"
send \"Y\r\"
expect \"Disallow root login remotely? (Press y|Y for Yes, any other key for No) : \"
send \"N\r\"
expect \"Remove test database and access to it? (Press y|Y for Yes, any other key for No) : \"
send \"Y\r\"
expect \"Reload privilege tables now? (Press y|Y for Yes, any other key for No) : \"
send \"Y\r\"
expect eof
"

# N.B. MySQL is automatically started at boot
