#!/usr/bin/env bash

#
# install_ruby
#
# Download the current version of ruby, and install it using RVM

# Install Ruby with RVM
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -sSL https://get.rvm.io | bash -s stable --ruby

# Update the env for the current session
source /home/`whoami`/.rvm/scripts/rvm

# Install Bundler
gem install bundle
