#!/usr/bin/env bash

#
# install_nodejs
#
# This script installs NodeJS via NVM

# Step 1: Download and install NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Step 2: Install the latest NodeJS
nvm install node

# N.B. To use node, run `nvm use node` in the shell
