#!/usr/bin/env bash

#
# install_supervisord
#
# This script installs Supervisord, a daemon that keeps programs alive even if
# they crash

# Install Supervisord
sudo yum -y install supervisor

# Start Supervisord when the server starts
sudo systemctl enable supervisord

# Get rid of the default configuration file that Supervisord creates so we don't
# accidentally use it
sudo rm /etc/supervisord.conf

# Create our own system-wide Supervisord configuration
cat << EOF | sudo tee /etc/supervisord.conf
; System-wide Supervisord configuration

; Open a socket where Supervisord will listen for XML-RPC & HTTP, such as from
; supervisorctl; you need unix_http_server and rpcinterface if you want to be able
; to interact with supervisord
[unix_http_server]
file=/tmp/supervisor.sock
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

; Configure how the actual supervisord program works: its log directory and pid file
[supervisord]
logfile=/var/log/supervisord/supervisord_main.log
pidfile=/tmp/supervisord.pid

; Point supervisorctl to the supervisord socket
; (Think of supervisord as a server, and supervisorctl as a client that needs to
; connect to it; this is the address it will connect with)
[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

; Load all configuration files for each individual daemon in this directory
; (Think of this like a sites-enabled directory in Apache -- it loads an arbitrary
; number of sub-configurations at runtime)
[include]
files = /etc/supervisord.d/conf.d/*.ini

EOF

# For some odd reason, CentOS ships with a /var/log/supervisor directory, which will
# only confuse us in the future; let's delete it
sudo rm -rf /var/log/supervisor

# Let's create a directory where we'll store log files
# N.B., this happens to be the same as the directory CentOS ships with (above), but
# we recreate it just to be safe and explicit
sudo mkdir /var/log/supervisord
sudo chown centos:centos /var/log/supervisord

# Make a directory where we'll store daemon configuration files for Supervisord
mkdir /etc/supervisord.d/conf.d
sudo chown centos:centos /etc/supervisord.d/conf.d

# Finally, start Supervisord
supervisord

# N.B. Place configuration files in /etc/supervisord.d/conf.d/my_daemon.ini, where my_file
# is the daemon you wish to create; for example, django.ini. This is how you create an
# actual daemon to be managed by Supervisord.

