#!/usr/bin/env bash

#
# install_heroku_cli
#
# Install the Heroku CLI
#
# See https://devcenter.heroku.com/articles/heroku-cli

# This is the only functional way to install Heroku on CentOS:
# - "snap" doesn't suppor CentOS
# - the "cli-assets.heroku.com/install.sh" script has bugs
# - the Tarballs have no installation instructions
# - there is no yum repository or distribution
npm install -g heroku
