#!/usr/bin/env bash

#
# install_python_2
#
# Set up a basic install of Python 2 (2.7.12, specifically), complete with setuptools, pip, and virtualenv
# (Why would anyone want Python without setuptools, pip, and virtualenv?)
#
# Inspiration:
# - https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

# Install the CentOS development tools, if we don't already have it;
# these are needed so that we can compile Python from source
sudo yum groupinstall -y 'development tools'

# If you want to be able to do 'import ____' and for it to work, you
# better have these packages on your system before you compile Python
sudo yum install -y zlib-dev openssl-devel sqlite-devel bzip2-devel

# Python has to be a special snowflake and compress its source with .xz,
# so we install a package to unzip those kinds of files
sudo yum install -y xz-libs

# We're going to download and compile in a new /opt/install_python_2 director
sudo mkdir /opt/install_python_2
cd /opt/install_python_2
sudo chown centos:centos /opt/install_python_2

# Download the Python 2.7.12 source
curl -O https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz

# "Unzip" the Python source
xz -d Python-2.7.12.tar.xz
tar -xvf Python-2.7.12.tar

# Configure, build, and install Python
cd /opt/install_python_2/Python-2.7.12
./configure --prefix=/usr/local
make
sudo make altinstall

# Install setuptools
curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo /usr/local/bin/python2.7

# Install pip
curl https://bootstrap.pypa.io/get-pip.py | sudo /usr/local/bin/python2.7

# Install virtualenv
sudo /usr/local/bin/pip install virtualenv

# Clean up the /opt/install_python_2 folder since we're done with it
sudo rm -rf /opt/install_python_2
