#!/usr/bin/env bash

#
# install_nginx
#
# This script installs a vanilla Nginx; if you plan to run a web server, a reverse
# proxy, load balancer, or cache, you'll probably need this

# Install Nginx
sudo yum -y install epel-release
sudo yum -y install nginx

# Start Nginx now
sudo systemctl start nginx

# Start Nginx when the system starts
sudo systemctl enable nginx

# N.B. This is how you should start and stop Nginx in the future
# sudo systemctl start nginx
# sudo systemctl stop nginx

