#!/usr/bin/env bash

#
# install_nginx
#
# This script installs a vanilla Nginx, for use as a web server, reverse
# proxy, load balancer, or cache

# Install Nginx
sudo yum -y install epel-release
sudo yum -y install nginx

# Start Nginx now
sudo systemctl start nginx

# Start Nginx when the system starts
sudo systemctl enable nginx

# N.B. This is how you should start and stop Nginx in the future
# sudo systemctl start nginx
# sudo systemctl stop nginx

